export interface Artist {
  id: number;
  name: string;
  category: string;
  location: string;
  priceRange: { min: number; max: number };
  image: string | null;
}

export const artists: Artist[] = [
  {
    id: 1,
    name: "Rohan",
    category: "DJ",
    location: "Mumbai",
    priceRange: { min: 10000, max: 20000 },
    image: null,
  },
  {
    id: 2,
    name: "Anjali",
    category: "Singer",
    location: "Delhi",
    priceRange: { min: 5000, max: 8000 },
    image: null,
  },
  {
    id: 3,
    name: "Meera",
    category: "Dancer",
    location: "Bangalore",
    priceRange: { min: 8000, max: 15000 },
    image: null,
  },
  {
    id: 4,
    name: "Yash",
    category: "Speaker",
    location: "Pune",
    priceRange: { min: 12000, max: 25000 },
    image: null,
  },
  {
    id: 5,
    name: "Tanya",
    category: "Dancer",
    location: "Chennai",
    priceRange: { min: 6000, max: 10000 },
    image: null,
  },
  {
    id: 6,
    name: "Karan",
    category: "DJ",
    location: "Hyderabad",
    priceRange: { min: 15000, max: 30000 },
    image: null,
  },
  {
    id: 7,
    name: "Sneha",
    category: "Singer",
    location: "Kolkata",
    priceRange: { min: 7000, max: 12000 },
    image: null,
  },
  {
    id: 8,
    name: "Vikram",
    category: "Dancer",
    location: "Ahmedabad",
    priceRange: { min: 9000, max: 18000 },
    image: null,
  },
  {
    id: 9,
    name: "Pooja",
    category: "Speaker",
    location: "Mumbai",
    priceRange: { min: 5000, max: 9000 },
    image: null,
  },
  {
    id: 10,
    name: "Arjun",
    category: "DJ",
    location: "Delhi",
    priceRange: { min: 20000, max: 35000 },
    image: null,
  },
  {
    id: 11,
    name: "Nisha",
    category: "Singer",
    location: "Pune",
    priceRange: { min: 10000, max: 18000 },
    image: null,
  },
  {
    id: 12,
    name: "Rajat",
    category: "DJ",
    location: "Chandigarh",
    priceRange: { min: 12000, max: 22000 },
    image: null,
  },
  {
    id: 13,
    name: "Divya",
    category: "Dancer",
    location: "Lucknow",
    priceRange: { min: 6000, max: 11000 },
    image: null,
  },
  {
    id: 14,
    name: "Imran",
    category: "Speaker",
    location: "Nagpur",
    priceRange: { min: 14000, max: 20000 },
    image: null,
  },
  {
    id: 15,
    name: "Farah",
    category: "Singer",
    location: "Jaipur",
    priceRange: { min: 9000, max: 14000 },
    image: null,
  },
  {
    id: 16,
    name: "Amit",
    category: "DJ",
    location: "Surat",
    priceRange: { min: 8000, max: 17000 },
    image: null,
  },
  {
    id: 17,
    name: "Simran",
    category: "Dancer",
    location: "Bhopal",
    priceRange: { min: 10000, max: 16000 },
    image: null,
  },
  {
    id: 18,
    name: "Neeraj",
    category: "Speaker",
    location: "Indore",
    priceRange: { min: 6000, max: 13000 },
    image: null,
  },
  {
    id: 19,
    name: "Priya",
    category: "Singer",
    location: "Thane",
    priceRange: { min: 11000, max: 19000 },
    image: null,
  },
  {
    id: 20,
    name: "Rahul",
    category: "DJ",
    location: "Vijayawada",
    priceRange: { min: 7000, max: 15000 },
    image: null,
  },
  {
    id: 21,
    name: "Ayesha",
    category: "Dancer",
    location: "Amritsar",
    priceRange: { min: 5000, max: 9000 },
    image: null,
  },
  {
    id: 22,
    name: "Manoj",
    category: "Speaker",
    location: "Patna",
    priceRange: { min: 8000, max: 12000 },
    image: null,
  },
  {
    id: 23,
    name: "Isha",
    category: "Singer",
    location: "Nashik",
    priceRange: { min: 13000, max: 20000 },
    image: null,
  },
  {
    id: 24,
    name: "Dev",
    category: "DJ",
    location: "Guwahati",
    priceRange: { min: 6000, max: 14000 },
    image: null,
  },
  {
    id: 25,
    name: "Riya",
    category: "Dancer",
    location: "Kochi",
    priceRange: { min: 9000, max: 17000 },
    image: null,
  },
  {
    id: 26,
    name: "Sagar",
    category: "Speaker",
    location: "Vadodara",
    priceRange: { min: 7000, max: 10000 },
    image: null,
  },
  {
    id: 27,
    name: "Neha",
    category: "Singer",
    location: "Jodhpur",
    priceRange: { min: 8000, max: 13000 },
    image: null,
  },
  {
    id: 28,
    name: "Tarun",
    category: "DJ",
    location: "Raipur",
    priceRange: { min: 10000, max: 19000 },
    image: null,
  },
  {
    id: 29,
    name: "Sana",
    category: "Dancer",
    location: "Ranchi",
    priceRange: { min: 6000, max: 11000 },
    image: null,
  },
  {
    id: 30,
    name: "Nitin",
    category: "Speaker",
    location: "Dehradun",
    priceRange: { min: 9000, max: 16000 },
    image: null,
  },
];
